'------------------------------------------------------------------------------
'<auto-generated>
'    This code was generated by a tool.
'    Runtime Version: 12.0.0.0
' 
'    Changes to this file may cause incorrect behavior and will be lost if
'    the code is regenerated.
'</auto-generated>
'------------------------------------------------------------------------------

Namespace Global.Madjic.Edi.Dom.DataElements
    '''<summary>Currency Code</summary>
    '''<remarks>
    '''<para>Code (Standard ISO) for country in whose currency the charges are specified</para>
    '''</remarks>
    Partial Friend Class Element100
        Inherits IdentifierElement

        Public Sub New()
            MyBase.New(3, 3, Nothing, Nothing)
            Initialize
        End Sub

        Partial Private Sub Initialize()
        End Sub

        Friend Shared Function FromReader(fullElement As String, reader As EdiReader.SegmentReader) As Element100
            Dim rval As New Element100

            rval.Value = fullElement
            Return rval
        End Function
    End Class
End Namespace
